### ISSUE TITLE
1.20?

### ISSUE THREAD

**Issue by CodeF53** [artemisSystem/coyote-time#1]

**Comment by artemisSystem** [comment]
eventually. been meaning to rewrite the whole mod (a single mixin) to be cleaner and more compatible with other mods, as well as add some new features, and ran into some issues that i haven't bothered to look further into yet. when i do, i'll most likely release new versions for 1.18.1-1.19.4 and 1.20+ for both fabric and forge, if it doesn't cause any issues.

this doesn't really need to be an issue, but i appreaciate the interest

**Comment by CodeF53** [comment]
The only thing you need to update is to [change `if (!this.onGround)` to `if (!this.onGround())`](https://github.com/CodeF53/coyote-time/commit/64e655a3c33b1406483721b2f64d44970a0b221d), as 1.20 made `onGround` private.

This works from 1.16 to 1.20.1

I made this issue as something to be closed by the pull request I was making

**Comment by artemisSystem** [comment]
i don't see why you would need to open an issue to open a PR. just open the pr in the case. but still, i probably wouldn't merge it, because i want to change up the code anyway
